### ISSUE TITLE
v1.0 Tracking Issue

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#3234]
@xonsh/xore, all, This is the great xonsh v1.0 tracking issue. The following items (in no particular order) are considered blockers for v1.0. Please feel free to add to this as needed. This list was developed at the very successful SciPy 2019 sprints, but of course, not everyone was there.

* [x] Job Control
* [ ] Write a manual
* [x] Make a landing page for the website, #3670 https://github.com/xonsh/landing-page-dev
* [ ] Reduce amount CLI wizard displays
* [x] Web xonfig application (like fish), #3226
* [ ] Develop governance documentation, including a community site for xontirbs
* [x] Environment registration / deregistration API, #3227 
* [x] Strip out `history replay` (done as part of #3377 )
* [ ] Remove threadable subproc notion

Topics pushed off to 2.0 include:

* Async execution interface for subprocesses. 
* Moving Popen capabilties to another library (slug)

As always, help for any of these points is extremely welcome!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment]
I propose we also strip out `history replay`.  Votes in favor / against?

**Comment by scopatz** [comment]
I am in favor of removing `history replay`

**Comment by scopatz** [comment]
or at least moving it to a xontrib or something

**Comment by astronouth7303** [comment]
I should really revisit slug. I still feel like having an actual posix-model process library (with virtual process support) would help a lot of the issues. Remove foreground/background weirdness, let us do proper posix session foreground/background process groups, etc.

**Comment by scopatz** [comment]
Yeah, I agree. I think slug is closer to a 2.0 issue at this point though.  I think it is important for us to get a "stable" v1.0 out for users, even though there are a lot of improvements we would all want to see in v1.0

**Comment by scopatz** [comment]
@dotsdl - where is that branch that you were working on for environment variable registration?

**Comment by scopatz** [comment]
Are we in a "good enough" spot for job control do we think?

**Comment by gforsyth** [comment]
> Are we in a "good enough" spot for job control do we think?

I think we need to figure out if any xonsh users use job control at all frequently.  Maybe we can ping some folks on some of the previous job control issues and see if things are working?

**Comment by gforsyth** [comment]
although, on further reflection, maybe we just say we're good enough for now.

**Comment by scopatz** [comment]
Yeah, I think a big subprocess refactor is going to be needed to get it in a better space than it is right now.  I do want to do this, but I think that 1.0 might be more important

**Comment by gforsyth** [comment]
It certainly won't change the api for backgrounding, so if it happens for 1.1 or 1.* we won't have pinned ourselves in by letting it be a little broken for 1.0.

**Comment by laloch** [comment]
What about Python 3.9 support? Expected v3.9.0 release date is on 2020-10-05.

**Comment by gforsyth** [comment]
Or, realistically, 3.8 support, since while we run under 3.8 we don't support the walrus operator.

3.9 scares me a bit -- not sure what the implications are re: the PEG parser

**Comment by laloch** [comment]
> Or, realistically, 3.8 support, since while we run under 3.8 we don't support the walrus operator.

Of course! I completely forgot about that nuisance.

> 3.9 scares me a bit -- not sure what the implications are re: the PEG parser

The worst part will be conversion of the parser tests. The PEG parser produces somewhat different AST. Currently, I have 27 parser tests failing in Python 3.9.0b5 mostly because the new parser creates `ast.Subscript` nodes where `ast.Call` are expected. Other class of differences is due to deprecation of nodes representing constants in favor of `ast.Constant`.

**Comment by laloch** [comment]
Regarding missing Python 3.8 features:
- [x] assignment expressions #3675
- [x] f-strings self-documenting expressions #3660
- [ ] possitional-only arguments are still to be implemented

**Comment by laloch** [comment]
This is in reply to https://github.com/xonsh/xonsh/pull/3873#issuecomment-710689514.

@scopatz, I'm glad you reconsidered refactoring the subprocess/job control code prior to the v1.0 release. Lately I've been thinking quite a lot about possible solutions. Unfortunately, I couldn't come with a portable one so far. There's already a lot of issues on Linux/POSIX systems, but on Windows some features are virtually impossible to implement. I'm looking forward to your ideas.

Regarding my suggestion of feature freeze, that was mostly a rant and I'm sorry about that. I could not help venting my frustration of my history loading twenty times slower than it used to be, of erratic completion behavior, which used to work just fine and of that annoying NO_COLOR deprecation warning that pops out each time I spawn the shell without any suggestion about where the unfortunate color code is being used.

**Comment by anki-code** [comment]
> without any suggestion about where the unfortunate color code is being used.

A bit comment: if you take closer look to the traceback along with warning you can catch the place. For example it could have `self._get_prompt_tokens("PROMPT"` that points to `$PROMPT`.

**Comment by anki-code** [comment]
I agree with @laloch about stabilisation the core functionality (subprocess logic). When I use the prompt with amazing xontribs and python along with shell I'm really happy. But when I try to do some devops/scripting actions and run xonsh script from xonsh or catch some output I'm happy too but I'm facing with unpredictable errors (they have been reported). It happening not so often but it makes apprehansion and doubts to the next tries.

For example I understand that `subprocess.Popen` works much better sometimes than builtins and every uncontrolled error I've faced push me to the thoughts: python+popen vs xonsh.

**Comment by scopatz** [comment]
Thanks @laloch!  I think we can address a lot of the issues you brought up

>  Lately I've been thinking quite a lot about possible solutions. Unfortunately, I couldn't come with a portable one so far.

Yeah I think this is exactly the point.  What xonsh (ie the code I wrote, so I'll take the responsibility here), was trying to come up with a single-ish mechanism that worked cross platform.  I don't think this is possible, my current thinking is to have a single API but different implementations for each platform. This should help make the code more readable / maintainable all around.

> There's already a lot of issues on Linux/POSIX systems, but on Windows some features are virtually impossible to implement. I'm looking forward to your ideas.

Yeah, I agree some thing are just impossible / need to be done in a different way.  Windows, interestingly enough, has a whole API for reading from the console in a parallel thread.  This is sort of what we try do already. I am not sure how this interops with WSL and some of the console changes that they have been making, but I hope that on WSL they'll allow PTYs.

>  could not help venting my frustration of my history loading twenty times slower than it used to be, 

Oooof that is bad... I am not seeing that. Maybe I missed an issue about that.  We should definitely fix that.

> of erratic completion behavior, which used to work just fine 

Yeah, there has been some churn there, sadly.

> and of that annoying NO_COLOR deprecation warning that pops out each time I spawn the shell without any suggestion about where the unfortunate color code is being used.

Yeah. That was also a mistake. We did add a traceback though. Did that help? I totally understand the frustration here though. I had to go back and put in a PR for all of the places NO_COLOR was missed in xonsh itself! Still, I am glad that band-aid was eventually ripped off.

**Comment by scopatz** [comment]
Thank for being such a great user/developer @anki-code!

> I've notices that sometimes the execution of this command from xonsh raises ioctl exceptions.

Does this happen only on WSL? Or is it true on native Linux too?

**Comment by anki-code** [comment]
I'm not using WSL. Just tried to understand how far it from pure linux some times.

It's true for native Linux. I haven't traceback now but two days ago I started important work and faced with this again when run `xonsh script.xsh` from xonsh. It was on pure ubuntu 18. I had no time to debug and I run this command from bash.

**Comment by laloch** [comment]
> my current thinking is to have a single API but different implementations for each platform. This should help make the code more readable / maintainable all around.

Yeah, we still have Slug, which is quite well laid out, but I still don't know how to implement virtual subprocesses or how to migrate Python callable execution into a real subprocess on Windows.
I think it's important (essential?) for a single Xonsh script to behave consistently across all the supported platforms.

> but I hope that on WSL they'll allow PTYs.

They do, if I remember correctly.

> > could not help venting my frustration of my history loading twenty times slower than it used to be,
> 
> Oooof that is bad... I am not seeing that.

Yeah, it is pretty bad and I'm not exaggerating. I never experienced the slow startup issue some users report. For me the shell used to be up and running in ~400ms including loading several years worth of history. And then the damn threaded history change happened. Now the same history (plus few weeks) takes ~10s to load on the very same machine.

> Maybe I missed an issue about that. We should definitely fix that.

No you didn't. I want to do some measuring and analysis first.
 
> > and of that annoying NO_COLOR deprecation warning that pops out each time I spawn the shell without any suggestion about where the unfortunate color code is being used.
> 
> Yeah. That was also a mistake. We did add a traceback though. Did that help? I totally understand the frustration here though. I had to go back and put in a PR for all of the places NO_COLOR was missed in xonsh itself!

The cleanup did help. Thank you.

**Comment by scopatz** [comment]
> Now the same history (plus few weeks) takes ~10s to load on the very same machine.

Yeah we should track that down and revert or fix

**Comment by anki-code** [comment]
I'm going to close this because we have no plans to release 1.0 in near future.

I think we can talk about version 1.0 after [improving threading](https://github.com/xonsh/xonsh/issues?q=is%3Aissue+is%3Aopen+label%3Athreading) and [rewrite executer (slugification)](https://github.com/xonsh/xonsh/issues/2159).
