### ISSUE TITLE
Refactoring: environment variables

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#5149]
Refactoring:

### First step

- [x] In completion search by substring instead of search by lprefix. Solved in #5388.
- [x] Fix setting variable using `xonsh -DVAR=VAL`. Solved in #5396.
- [x] Group env variables by xonsh components. First step is in #5501

### Second step

Xonsh has [many environment variables](https://xon.sh/envvars.html) and part of them are marked as `XONSH_` and the rest not. I suggest to add `XONSH_` prefix to all environment variables that are related to xonsh itself i.e. rename `RAISE_SUBPROC_ERROR` to `XONSH_RAISE_SUBPROC_ERROR` etc. Pros: Clear understanding of `env`. The way to remove xonsh env variables by running `env | grep -v XONSH_ | grep -v XONTRIB_`.

- [x] Implemet an approach to mark env variable as deprecated and provide backwards compatibility (e.g the state of `RAISE_SUBPROC_ERROR` should update `XONSH_SUBPROC_RAISE_ERROR` values). Done in - https://github.com/xonsh/xonsh/pull/5961

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by eugenesvk** [comment]
Could we also replace or at least add an alternative naming which is lowercase? It's rather unergonomic to type all these long names ALL UPPERCASE, especially in cases like `env | grep -v XONSH_ | grep -v XONTRIB_` where you can't use auto-complete

**Comment by eugenesvk** [comment]
1. And it's a bad standard forcing needless pinky Shifts.
2. The problem isn't only with grep , simply typing these long XONSH_SUBPROC_CAPTURED_PRINT_STDERR is already an issue
3. Doesn't help with the $XONSH env vars

**Comment by anki-code** [comment]
What you can do to help:
1. Grab the setting group e.g. [PTKSettings](https://github.com/xonsh/xonsh/blob/ea84fd5781810ecf338455c43f066c25f7c8f83c/xonsh/environ.py#L1714). Tell us about the group you will work.
2. [Rename variables](https://github.com/xonsh/xonsh/pull/5961/files#diff-802a31882240ac8ba6fdeb8196316c48bf5015d401b36b8cc40b8550aaafc397R1728) by setting [sync and deprecated markers](https://github.com/xonsh/xonsh/pull/5961/files#diff-802a31882240ac8ba6fdeb8196316c48bf5015d401b36b8cc40b8550aaafc397R2028-R2033). 
3. If you see that behavior behind env variable is common choose the name like `XONSH_PROMPT_SUGGESTION` instead of `XONSH_PTK_SUGGESTION`. The list of xonsh components could be found in [1](https://github.com/xonsh/xonsh/issues/5538) or [2](https://github.com/xonsh/xonsh/labels).
4. Test is not needed. Just replace the name.
5. Search for deprecated variable in the code and replace to new (I'm [using](https://github.com/anki-code/xonsh-developer-toolkit?tab=readme-ov-file#pycharm) pycharm - click xonsh press `Cmd+Shift+F` to search by text or `grep -R --color=auto "VAR_NAME" ./xonsh` as well).
6. Open PR with changes.

**Comment by anki-code** [comment]
- [ ] Rename XONSH_STORE_STDOUT to XONSH_HISTORY_STORE_OUTPUT (check that it's right)
